In [1]:
# 필요한 라이브러리 불러오기
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline
# 한글 깨짐 현상 방지
from matplotlib import pyplot as plt
plt.rc('font', family='NanumGothic')
# ▶ Warnings 제거
import warnings
warnings.filterwarnings('ignore')
# 시간측정을 위한 time
import time
import csv
pd.options.display.float_format = '{:.5f}'.format

In [2]:
#데이터 불러오기
df = pd.read_csv('소득계산.csv')

In [3]:
#null값 확인
df.isnull().sum()

시도           0
시군구         18
총 수입금액       0
총 신고인원       0
1인당 수입금액     0
dtype: int64

In [4]:
#null값 제거
df_eda = df.dropna().reset_index(drop=True) #NaM 제거 후 reset_index
df_eda

          시도   시군구      총 수입금액   총 신고인원  1인당 수입금액
0      서울특별시   강남구  50,768,494  341,643 148.60000
1      서울특별시   강동구  17,789,049  269,559  65.99000
2      서울특별시   강북구   7,863,222  155,154  50.68000
3      서울특별시   강서구  20,868,756  349,033  59.79000
4      서울특별시   관악구  15,274,980  310,532  49.19000
..       ...   ...         ...      ...       ...
223     경상남도   함안군   1,939,710   28,587  67.85000
224     경상남도   함양군     792,693   12,866  61.61000
225     경상남도   합천군     856,190   12,742  67.19000
226  제주특별자치도  서귀포시   9,622,805  197,062  48.83000
227  제주특별자치도   제주시  12,651,493  122,897 102.94000

[228 rows x 5 columns]

In [5]:
#8도 분류 - 220726 추가

In [6]:
do1 = ['서울특별시','인천광역시','경기도']
do2 = ['강원도']
do3 = ['충청북도']
do4 = ['충청남도' ,'세종특별자치시', '대전광역시']
do5 = ['경상북도', '대구광역시']
do6 = ['부산광역시', '울산광역시' ,'경상남도']
do7 = ['전라남도', '광주광역시']
do8 = ['전라북도']
do9 = ['제주도']

all_list = []
all_list.append(do1)
all_list.append(do2)
all_list.append(do3)
all_list.append(do4)
all_list.append(do5)
all_list.append(do6)
all_list.append(do7)
all_list.append(do8)
all_list.append(do9)
print(all_list)

[['서울특별시', '인천광역시', '경기도'], ['강원도'], ['충청북도'], ['충청남도', '세종특별자치시', '대전광역시'], ['경상북도', '대구광역시'], ['부산광역시', '울산광역시', '경상남도'], ['전라남도', '광주광역시'], ['전라북도'], ['제주도']]

# 원하는 동 클릭

In [7]:
#1. 행정동 입력 시 해당 지역의 시도 추출 후 filter
gu = '종로구'
dong = '삼청동'

#시도 추출
sido = list(df_eda[df_eda['시군구']==gu]['시도'])[0]
print(sido)

#8도 별로 나눠진 시도 추출
text = sido
sido_list = [x for x in all_list if text in x]
print(sido_list)

서울특별시
[['서울특별시', '인천광역시', '경기도']]

In [8]:
df_eda_tot = pd.DataFrame()
for sido in sido_list[0] :
    print(sido)
    df_eda_sido =df_eda[df_eda['시도']==sido]
    df_eda_tot = pd.concat([df_eda_tot, df_eda_sido])
df_eda_tot.head(70)

서울특별시
인천광역시
경기도

       시도  시군구      총 수입금액   총 신고인원  1인당 수입금액
0   서울특별시  강남구  50,768,494  341,643 148.60000
1   서울특별시  강동구  17,789,049  269,559  65.99000
2   서울특별시  강북구   7,863,222  155,154  50.68000
3   서울특별시  강서구  20,868,756  349,033  59.79000
4   서울특별시  관악구  15,274,980  310,532  49.19000
..    ...  ...         ...      ...       ...
61    경기도  파주시  16,776,606  267,440  62.73000
62    경기도  평택시  18,837,165  314,573  59.88000
63    경기도  포천시   5,649,231   84,856  66.57000
64    경기도  하남시  13,658,786  186,887  73.09000
65    경기도  화성시  38,943,836  535,673  72.70000

[66 rows x 5 columns]

In [9]:
#2. 기준값 추출
df_search = df_eda_tot[df_eda_tot['시군구']==gu]['1인당 수입금액']
df_search

22   93.13000
Name: 1인당 수입금액, dtype: float64

In [10]:
#3. 차이를 뺀 값을 나타내는 컬럼 추가
df_eda_tot['차이'] = df_eda_tot['1인당 수입금액'] - float(df_search)
df_eda_tot

       시도  시군구      총 수입금액   총 신고인원  1인당 수입금액        차이
0   서울특별시  강남구  50,768,494  341,643 148.60000  55.47000
1   서울특별시  강동구  17,789,049  269,559  65.99000 -27.14000
2   서울특별시  강북구   7,863,222  155,154  50.68000 -42.45000
3   서울특별시  강서구  20,868,756  349,033  59.79000 -33.34000
4   서울특별시  관악구  15,274,980  310,532  49.19000 -43.94000
..    ...  ...         ...      ...       ...       ...
61    경기도  파주시  16,776,606  267,440  62.73000 -30.40000
62    경기도  평택시  18,837,165  314,573  59.88000 -33.25000
63    경기도  포천시   5,649,231   84,856  66.57000 -26.56000
64    경기도  하남시  13,658,786  186,887  73.09000 -20.04000
65    경기도  화성시  38,943,836  535,673  72.70000 -20.43000

[66 rows x 6 columns]

In [11]:
#4. 절대값으로 orderby 
df_eda_tot = df_eda_tot.sort_values('차이',ascending=True,key=lambda col: abs(col))
#df_eda = df_eda.sort_values('차이',ascending=True)
print(len(df_eda))
df_eda_tot.head(30)

228

       시도       시군구      총 수입금액   총 신고인원  1인당 수입금액        차이
22  서울특별시       종로구   7,821,477   83,986  93.13000   0.00000
29  인천광역시  미추홀구(남구)   7,915,520   86,197  91.83000  -1.30000
23  서울특별시        중구   6,808,822   74,735  91.11000  -2.02000
32  인천광역시       연수구  21,059,437  232,912  90.42000  -2.71000
37    경기도       과천시   4,002,896   41,004  97.62000   4.49000
17  서울특별시       송파구  36,029,296  412,042  87.44000  -5.69000
15  서울특별시       성동구  14,828,250  175,236  84.62000  -8.51000
18  서울특별시       양천구  21,381,385  258,807  82.62000 -10.51000
46    경기도       성남시  44,595,231  554,713  80.39000 -12.74000
12  서울특별시       마포구  17,117,787  232,304  73.69000 -19.44000
57    경기도       용인시  44,700,354  611,318  73.12000 -20.01000
64    경기도       하남시  13,658,786  186,887  73.09000 -20.04000
65    경기도       화성시  38,943,836  535,673  72.70000 -20.43000
53    경기도       양평군   3,885,347   53,726  72.32000 -20.81000
58    경기도       의왕시   6,963,708   97,438  71.47000 -21.66000
19  서울특별시      영등포구  17,841,237  251,013  71.08000 -22.05000
16  서울특별시       성북구  16,586,201  234,652  70.68000 -22.45000
43    경기도      남양주시  27,581,796  391,323  70.48000 -22.65000
42    경기도       김포시  20,173,246  287,937  70.06000 -23.07000
36    경기도       고양시  43,233,884  620,743  69.65000 -23.48000
25  인천광역시       강화군   1,971,317   28,488  69.20000 -23.93000
31  인천광역시        서구  21,555,356  317,682  67.85000 -25.28000
38    경기도       광명시  11,498,988  169,466  67.85000 -25.28000
33  인천광역시       옹진군     654,946    9,654  67.84000 -25.29000
47    경기도       수원시  47,166,891  696,853  67.69000 -25.44000
27  인천광역시       남동구  16,044,593  239,623  66.96000 -26.17000
11  서울특별시       동작구  15,773,178  235,610  66.95000 -26.18000
39    경기도       광주시  15,416,563  230,931  66.76000 -26.37000
51    경기도       안양시  21,478,973  321,899  66.73000 -26.40000
63    경기도       포천시   5,649,231   84,856  66.57000 -26.56000

In [22]:
df_eda_tot.to_csv('종로구삼청동_round1_시군구_220801.csv',encoding = 'UTF-8-sig', index=False)

In [12]:
#5. 차이10% 이내로 짜르기
#228개 시군구 중 10%
Gizun_val = 0.1 #10%
df_round1 = df_eda_tot[abs(df_eda_tot['차이'])<= (float(df_search)*Gizun_val)]
print(len(df_round1))
df_round1

#list로 추출
round1_list = list(set(df_round1['시군구'].tolist()))
print(round1_list)

round_sido_list = list(set(df_round1['시도'].tolist()))
print(round_sido_list)

7
['송파구', '미추홀구(남구)', '중구', '종로구', '연수구', '성동구', '과천시']
['인천광역시', '서울특별시', '경기도']

# Round2

In [13]:
#Round2 Data 불러오기
df2 = pd.read_csv('df_유사지역_raw.csv')
df2.head(5)

,행정동코드,시도명,시군구명,행정동명,총인구수,20대미만,20대,30대,40대,50대,...,남여성비(여),연령비_20미만,연령비_20,연령비_30,연령비_40,연령비_50,연령비_60,연령비_70이상,운영가맹점수,가맹점당인구수
0,1111051500,서울특별시,종로구,청운효자동,11978,1886,1566,1581,2075,1925,...,0.53865,0.15746,0.13074,0.13199,0.17323,0.16071,0.11747,0.12840,797,15.02886
1,1111053000,서울특별시,종로구,사직동,9372,1233,1202,1447,1489,1533,...,0.55186,0.13156,0.12825,0.15440,0.15888,0.16357,0.12879,0.13455,2473,3.78973
2,1111054000,서울특별시,종로구,삼청동,2456,273,320,303,348,385,...,0.52443,0.11116,0.13029,0.12337,0.14169,0.15676,0.16572,0.17101,783,3.13665
3,1111055000,서울특별시,종로구,부암동,9579,1351,1227,1210,1551,1682,...,0.52291,0.14104,0.12809,0.12632,0.16192,0.17559,0.14125,0.12580,443,21.62302
4,1111056000,서울특별시,종로구,평창동,18152,2727,2342,2200,2690,3256,...,0.53410,0.15023,0.12902,0.12120,0.14819,0.17937,0.14759,0.12439,538,33.73978

In [14]:
#round_sido_list 에 있는 시로 포함된 애들만 가져오기

df_concat_sido = pd.DataFrame()
for i in round_sido_list:
    df_i = df2[df2['시도명']== i]
    df_concat_sido = pd.concat([df_concat_sido,df_i],axis=0)

#round1_list에 있는 시군구에 포함된 "행정동" 모두 불러오기
df_concat = pd.DataFrame()
for i in round1_list:
    df_i = df_concat_sido[df_concat_sido['시군구명']== i]
    df_concat = pd.concat([df_concat,df_i],axis=0)

print(df_concat['시군구명'].unique())
print(df_concat['행정동명'].unique())
df_concat

['송파구' '중구' '종로구' '연수구' '성동구' '과천시']
['풍납1동' '풍납2동' '거여1동' '거여2동' '마천1동' '마천2동' '방이1동' '방이2동' '오륜동' '오금동'
 '송파1동' '송파2동' '석촌동' '삼전동' '가락본동' '가락1동' '가락2동' '문정1동' '문정2동' '장지동' '위례동'
 '잠실본동' '잠실2동' '잠실3동' '잠실4동' '잠실6동' '잠실7동' '연안동' '신포동' '신흥동' '도원동' '율목동'
 '동인천동' '개항동' '영종동' '영종1동' '운서동' '용유동' '소공동' '회현동' '명동' '필동' '장충동' '광희동'
 '을지로동' '신당동' '다산동' '약수동' '청구동' '신당5동' '동화동' '황학동' '중림동' '청운효자동' '사직동'
 '삼청동' '부암동' '평창동' '무악동' '교남동' '가회동' '종로1·2·3·4가동' '종로5·6가동' '이화동' '혜화동'
 '창신1동' '창신2동' '창신3동' '숭인1동' '숭인2동' '옥련1동' '옥련2동' '선학동' '연수1동' '연수2동'
 '연수3동' '청학동' '동춘1동' '동춘2동' '동춘3동' '송도1동' '송도2동' '송도3동' '송도4동' '송도5동'
 '왕십리2동' '왕십리도선동' '마장동' '사근동' '행당1동' '행당2동' '응봉동' '금호1가동' '금호2·3가동'
 '금호4가동' '옥수동' '성수1가1동' '성수1가2동' '성수2가1동' '성수2가3동' '송정동' '용답동' '중앙동' '갈현동'
 '별양동' '부림동' '과천동' '문원동']

,행정동코드,시도명,시군구명,행정동명,총인구수,20대미만,20대,30대,40대,50대,...,남여성비(여),연령비_20미만,연령비_20,연령비_30,연령비_40,연령비_50,연령비_60,연령비_70이상,운영가맹점수,가맹점당인구수
380,1171051000,서울특별시,송파구,풍납1동,12869,1428,1553,1771,1813,2205,...,0.51045,0.11096,0.12068,0.13762,0.14088,0.17134,0.18867,0.12985,485,26.53402
381,1171052000,서울특별시,송파구,풍납2동,24785,3788,3673,4066,3958,3631,...,0.52483,0.15283,0.14819,0.16405,0.15969,0.14650,0.13496,0.09377,779,31.81643
382,1171053100,서울특별시,송파구,거여1동,12539,1507,1778,1714,1772,2252,...,0.49478,0.12019,0.14180,0.13669,0.14132,0.17960,0.15950,0.12090,582,21.54467
383,1171053200,서울특별시,송파구,거여2동,18726,2669,2170,2658,2877,3235,...,0.50817,0.14253,0.11588,0.14194,0.15364,0.17275,0.15332,0.11994,578,32.39792
384,1171054000,서울특별시,송파구,마천1동,18916,2344,2245,2130,2626,3506,...,0.48911,0.12392,0.11868,0.11260,0.13882,0.18535,0.17535,0.14527,497,38.06036
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1451,4129052000,경기도,과천시,갈현동,16891,4042,1953,2340,2999,2718,...,0.51311,0.23930,0.11562,0.13854,0.17755,0.16091,0.09911,0.06897,266,63.50000
1452,4129053000,경기도,과천시,별양동,13842,2417,1988,1880,1891,2544,...,0.51546,0.17461,0.14362,0.13582,0.13661,0.18379,0.13510,0.09045,811,17.06782
1453,4129054000,경기도,과천시,부림동,15002,2840,1988,2474,2146,2566,...,0.50620,0.18931,0.13252,0.16491,0.14305,0.17104,0.11718,0.08199,122,122.96721
1454,4129055000,경기도,과천시,과천동,9212,1157,1215,1586,1321,1507,...,0.47731,0.12560,0.13189,0.17217,0.14340,0.16359,0.15578,0.10758,765,12.04183
1455,4129056000,경기도,과천시,문원동,7473,1273,1040,960,1122,1310,...,0.51131,0.17035,0.13917,0.12846,0.15014,0.17530,0.12271,0.11388,171,43.70175

In [15]:
# #1. round1에서 추려진 시군구가 들어간 행정동 요소를 list로 전부 추출(계산을 위해)
df_concat_list= df_concat.values.tolist()
df_concat_list

[[1171051000,
  '서울특별시',
  '송파구',
  '풍납1동',
  12869,
  1428,
  1553,
  1771,
  1813,
  2205,
  2428,
  1671,
  0.489548527,
  0.510451473,
  0.110964333,
  0.120677597,
  0.13761753,
  0.140881187,
  0.171341985,
  0.188670448,
  0.129846919,
  485,
  26.53402062],
 [1171052000,
  '서울특별시',
  '송파구',
  '풍납2동',
  24785,
  3788,
  3673,
  4066,
  3958,
  3631,
  3345,
  2324,
  0.475166431,
  0.524833569,
  0.152834376,
  0.148194472,
  0.164050837,
  0.159693363,
  0.146499899,
  0.134960662,
  0.093766391,
  779,
  31.81643132],
 [1171053100,
  '서울특별시',
  '송파구',
  '거여1동',
  12539,
  1507,
  1778,
  1714,
  1772,
  2252,
  2000,
  1516,
  0.505223702,
  0.494776298,
  0.120185023,
  0.141797592,
  0.136693516,
  0.141319084,
  0.179599649,
  0.159502353,
  0.120902783,
  582,
  21.54467354],
 [1171053200,
  '서울특별시',
  '송파구',
  '거여2동',
  18726,
  2669,
  2170,
  2658,
  2877,
  3235,
  2871,
  2246,
  0.491829542,
  0.508170458,
  0.142529104,
  0.115881662,
  0.141941685,
  0.153636655,
  0.172754459,
  0.153316245,
  0.11994019,
  578,
  32.39792388],
 [1171054000,
  '서울특별시',
  '송파구',
  '마천1동',
  18916,
  2344,
  2245,
  2130,
  2626,
  3506,
  3317,
  2748,
  0.510890252,
  0.489109748,
  0.123916261,
  0.118682597,
  0.112603087,
  0.138824276,
  0.185345739,
  0.175354198,
  0.145273842,
  497,
  38.06036217],
 [1171055000,
  '서울특별시',
  '송파구',
  '마천2동',
  18713,
  2022,
  2322,
  2156,
  2593,
  3525,
  3533,
  2562,
  0.509592262,
  0.490407738,
  0.108053225,
  0.124084861,
  0.115214022,
  0.138566772,
  0.18837172,
  0.18879923,
  0.136910169,
  910,
  20.56373626],
 [1171056100,
  '서울특별시',
  '송파구',
  '방이1동',
  15682,
  2571,
  2355,
  2227,
  2481,
  2668,
  2073,
  1307,
  0.48176253,
  0.51823747,
  0.163945925,
  0.150172172,
  0.142009948,
  0.158206861,
  0.170131361,
  0.132189772,
  0.083343961,
  1060,
  14.79433962],
 [1171056200,
  '서울특별시',
  '송파구',
  '방이2동',
  26489,
  2295,
  5366,
  6230,
  3645,
  3572,
  3260,
  2121,
  0.464494696,
  0.535505304,
  0.086639737,
  0.202574654,
  0.235191966,
  0.137604289,
  0.134848428,
  0.123069954,
  0.080070973,
  2255,
  11.74678492],
 [1171056600,
  '서울특별시',
  '송파구',
  '오륜동',
  18061,
  3809,
  2106,
  1661,
  3146,
  3131,
  2623,
  1585,
  0.488566525,
  0.511433475,
  0.210896407,
  0.116604839,
  0.091966115,
  0.174187476,
  0.173356957,
  0.145230054,
  0.087758153,
  394,
  45.84010152],
 [1171057000,
  '서울특별시',
  '송파구',
  '오금동',
  38446,
  5687,
  5226,
  5444,
  5615,
  6763,
  5873,
  3838,
  0.484731832,
  0.515268168,
  0.14792176,
  0.135930916,
  0.141601207,
  0.146049004,
  0.175909067,
  0.152759715,
  0.099828331,
  1541,
  24.94873459],
 [1171058000,
  '서울특별시',
  '송파구',
  '송파1동',
  23845,
  2374,
  4334,
  5326,
  3343,
  3323,
  3073,
  2072,
  0.466722583,
  0.533277417,
  0.099559656,
  0.181757182,
  0.223359195,
  0.140197106,
  0.139358356,
  0.128873978,
  0.086894527,
  1729,
  13.79120879],
 [1171059000,
  '서울특별시',
  '송파구',
  '송파2동',
  19130,
  3265,
  2608,
  2737,
  2999,
  3129,
  2718,
  1674,
  0.482017773,
  0.517982227,
  0.170674334,
  0.136330371,
  0.143073706,
  0.156769472,
  0.163565081,
  0.142080502,
  0.087506534,
  744,
  25.71236559],
 [1171060000,
  '서울특별시',
  '송파구',
  '석촌동',
  31584,
  3286,
  5354,
  6799,
  4800,
  4632,
  3971,
  2742,
  0.477013678,
  0.522986322,
  0.10404002,
  0.169516211,
  0.215267224,
  0.151975684,
  0.146656535,
  0.125728217,
  0.086816109,
  2235,
  14.13154362],
 [1171061000,
  '서울특별시',
  '송파구',
  '삼전동',
  30325,
  3353,
  5145,
  6382,
  4975,
  4323,
  3709,
  2438,
  0.47004122,
  0.52995878,
  0.110568838,
  0.169661995,
  0.210453421,
  0.164056059,
  0.142555647,
  0.122308326,
  0.080395713,
  1607,
  18.87056627],
 [1171062000,
  '서울특별시',
  '송파구',
  '가락본동',
  26252,
  3335,
  3908,
  4599,
  3759,
  4558,
  3823,
  2270,
  0.49592412,
  0.50407588,
  0.12703794,
  0.148864848,
  0.175186652,
  0.14318909,
  0.173624867,
  0.145627,
  0.086469602,
  2269,
  11.56985456],
 [1171063100,
  '서울특별시',
  '송파구',
  '가락1동',
  27265,
  5410,
  3092,
  4793,
  4508,
  3957,
  3611,
  1894,
  0.484247203,
  0.515752797,
  0.198422886,
  0.113405465,
  0.175793141,
  0.16534018,
  0.14513112,
  0.132440858,
  0.069466349,
  1655,
  16.47432024],
 [1171063200,
  '서울특별시',
  '송파구',
  '가락2동',
  32229,
  5809,
  4390,
  4643,
  5470,
  5193,
  4244,
  2480,
  0.490862267,
  0.509137733,
  0.180241397,
  0.136212728,
  0.144062801,
  0.16972292,
  0.161128176,
  0.131682646,
  0.076949331,
  1338,
  24.08744395],
 [1171064100,
  '서울특별시',
  '송파구',
  '문정1동',
  20012,
  2678,
  3088,
  3414,
  2817,
  3277,
  3028,
  1710,
  0.495802518,
  0.504197482,
  0.133819708,
  0.154307416,
  0.170597641,
  0.140765541,
  0.163751749,
  0.151309214,
  0.085448731,
  960,
  20.84583333],
 [1171064200,
  '서울특별시',
  '송파구',
  '문정2동',
  28871,
  2939,
  5099,
  7250,
  4365,
  3503,
  3244,
  2471,
  0.459492224,
  0.540507776,
  0.101797652,
  0.17661321,
  0.251117038,
  0.151189775,
  0.121332825,
  0.112361886,
  0.085587614,
  3654,
  7.90120416],
 [1171064600,
  '서울특별시',
  '송파구',
  '장지동',
  29534,
  4858,
  3978,
  4602,
  4629,
  4784,
  4042,
  2641,
  0.483442812,
  0.516557188,
  0.164488386,
  0.134692219,
  0.15582041,
  0.156734611,
  0.161982799,
  0.136859213,
  0.089422361,
  909,
  32.49064906],
 [1171064700,
  '서울특별시',
  '송파구',
  '위례동',
  39095,
  11513,
  3586,
  6816,
  7710,
  4686,
  2971,
  1813,
  0.487069958,
  0.512930042,
  0.294487786,
  0.091725285,
  0.174344545,
  0.19721192,
  0.119861875,
  0.075994373,
  0.046374217,
  663,
  58.9668175],
 [1171065000,
  '서울특별시',
  '송파구',
  '잠실본동',
  27953,
  2856,
  4992,
  6017,
  4316,
  4031,
  3498,
  2243,
  0.474510786,
  0.525489214,
  0.102171502,
  0.178585483,
  0.215254177,
  0.154402032,
  0.144206346,
  0.125138626,
  0.080241835,
  2621,
  10.66501335],
 [1171067000,
  '서울특별시',
  '송파구',
  '잠실2동',
  35036,
  9508,
  3269,
  3512,
  8332,
  5124,
  3003,
  2288,
  0.478250942,
  0.521749058,
  0.271378011,
  0.09330403,
  0.100239753,
  0.237812536,
  0.146249572,
  0.085711839,
  0.065304258,
  706,
  49.62606232],
 [1171068000,
  '서울특별시',
  '송파구',
  '잠실3동',
  34338,
  7045,
  3685,
  3916,
  6186,
  5249,
  4783,
  3474,
  0.475770284,
  0.524229716,
  0.205166288,
  0.107315511,
  0.114042751,
  0.180150271,
  0.152862718,
  0.139291747,
  0.101170715,
  878,
  39.10933941],
 [1171069000,
  '서울특별시',
  '송파구',
  '잠실4동',
  21318,
  5048,
  1944,
  2716,
  4403,
  3015,
  2536,
  1656,
  0.479829252,
  0.520170748,
  0.236795197,
  0.091190543,
  0.127404072,
  0.206539075,
  0.141429778,
  0.118960503,
  0.077680833,
  291,
  73.25773196],
 [1171071000,
  '서울특별시',
  '송파구',
  '잠실6동',
  16775,
  3104,
  1931,
  2117,
  2771,
  2666,
  2479,
  1707,
  0.473621461,
  0.526378539,
  0.185037258,
  0.115111773,
  0.126199702,
  0.165186289,
  0.158926975,
  0.147779434,
  0.101758569,
  1349,
  12.43513714],
 [1171072000,
  '서울특별시',
  '송파구',
  '잠실7동',
  9550,
  1507,
  1225,
  934,
  1300,
  1676,
  1480,
  1428,
  0.466387435,
  0.533612565,
  0.157801047,
  0.128272251,
  0.097801047,
  0.136125654,
  0.175497382,
  0.154973822,
  0.149528796,
  113,
  84.51327434],
 [2811052000,
  '인천광역시',
  '중구',
  '연안동',
  6145,
  542,
  619,
  625,
  774,
  1228,
  1365,
  992,
  0.541253051,
  0.458746949,
  0.08820179,
  0.100732303,
  0.101708706,
  0.125956062,
  0.199837266,
  0.222131814,
  0.161432059,
  1184,
  5.190033784],
 [2811053000,
  '인천광역시',
  '중구',
  '신포동',
  5086,
  579,
  517,
  519,
  778,
  866,
  854,
  973,
  0.510224145,
  0.489775855,
  0.113841919,
  0.101651593,
  0.102044829,
  0.152968934,
  0.170271333,
  0.167911915,
  0.191309477,
  1065,
  4.775586854],
 [2811054000,
  '인천광역시',
  '중구',
  '신흥동',
  13241,
  1912,
  1602,
  1551,
  2013,
  2247,
  2121,
  1795,
  0.50857186,
  0.49142814,
  0.14439997,
  0.120987841,
  0.117136168,
  0.152027792,
  0.169700174,
  0.160184276,
  0.135563779,
  846,
  15.65130024],
 [2811056000,
  '인천광역시',
  '중구',
  '도원동',
  3925,
  360,
  424,
  345,
  525,
  705,
  773,
  793,
  0.509808917,
  0.490191083,
  0.091719745,
  0.108025478,
  0.087898089,
  0.133757962,
  0.179617834,
  0.196942675,
  0.202038217,
  143,
  27.44755245],
 [2811057000,
  '인천광역시',
  '중구',
  '율목동',
  3192,
  253,
  328,
  281,
  446,
  616,
  627,
  641,
  0.515037594,
  0.484962406,
  0.079260652,
  0.102756892,
  0.088032581,
  0.139724311,
  0.192982456,
  0.196428571,
  0.200814536,
  125,
  25.536],
 [2811058500,
  '인천광역시',
  '중구',
  '동인천동',
  5818,
  467,
  588,
  643,
  740,
  1077,
  1132,
  1171,
  0.529907185,
  0.470092815,
  0.080268133,
  0.101065658,
  0.110519079,
  0.127191475,
  0.18511516,
  0.19456858,
  0.201271915,
  1038,
  5.605009634],
 [2811061500,
  '인천광역시',
  '중구',
  '개항동',
  7022,
  677,
  740,
  675,
  933,
  1256,
  1384,
  1357,
  0.500996867,
  0.499003133,
  0.096411279,
  0.105383082,
  0.09612646,
  0.132868129,
  0.17886642,
  0.197094845,
  0.193249786,
  561,
  12.51693405],
 [2811062000,
  '인천광역시',
  '중구',
  '영종동',
  19131,
  2732,
  2512,
  2997,
  3140,
  3269,
  2778,
  1703,
  0.546495217,
  0.453504783,
  0.142804872,
  0.131305211,
  0.156656735,
  0.164131514,
  0.170874497,
  0.145209346,
  0.089017824,
  837,
  22.85663082],
 [2811062200,
  '인천광역시',
  '중구',
  '영종1동',
  44046,
  12063,
  3720,
  8612,
  9816,
  4795,
  3084,
  1956,
  0.502156836,
  0.497843164,
  0.273872769,
  0.084457158,
  0.195522862,
  0.222857921,
  0.108863461,
  0.070017709,
  0.044408119,
  1319,
  33.39347991],
 [2811062800,
  '인천광역시',
  '중구',
  '운서동',
  32080,
  5040,
  7645,
  5466,
  5623,
  4318,
  2122,
  1866,
  0.530174564,
  0.469825436,
  0.157107232,
  0.238310474,
  0.170386534,
  0.175280549,
  0.134600998,
  0.066147132,
  0.058167082,
  1789,
  17.93180548],
 [2811063000,
  '인천광역시',
  '중구',
  '용유동',
  3947,
  183,
  245,
  277,
  446,
  853,
  1076,
  867,
  0.556625285,
  0.443374715,
  0.046364327,
  0.06207246,
  0.070179883,
  0.112997213,
  0.216113504,
  0.27261211,
  0.219660502,
  1008,
  3.915674603],
 [1114052000,
  '서울특별시',
  '중구',
  '소공동',
  2250,
  294,
  251,
  501,
  504,
  305,
  243,
  152,
  0.478666667,
  0.521333333,
  0.130666667,
  0.111555556,
  0.222666667,
  0.224,
  0.135555556,
  0.108,
  0.067555556,
  2518,
  0.893566322],
 [1114054000,
  '서울특별시',
  '중구',
  '회현동',
  4784,
  389,
  492,
  520,
  648,
  891,
  1031,
  813,
  0.52006689,
  0.47993311,
  0.081312709,
  0.102842809,
  0.108695652,
  0.135451505,
  0.186245819,
  0.215510033,
  0.169941472,
  4422,
  1.08186341],
 [1114055000,
  '서울특별시',
  '중구',
  '명동',
  2884,
  209,
  384,
  403,
  406,
  489,
  519,
  474,
  0.437586685,
  0.562413315,
  0.072468793,
  0.133148405,
  0.139736477,
  0.140776699,
  0.169556172,
  0.179958391,
  0.164355062,
  3808,
  0.757352941],
 [1114057000,
  '서울특별시',
  '중구',
  '필동',
  4023,
  363,
  727,
  675,
  459,
  590,
  609,
  600,
  0.508327119,
  0.491672881,
  0.090231171,
  0.180710912,
  0.167785235,
  0.11409396,
  0.146656724,
  0.151379567,
  0.149142431,
  1688,
  2.383293839],
 [1114058000,
  '서울특별시',
  '중구',
  '장충동',
  4590,
  417,
  1223,
  654,
  561,
  602,
  542,
  591,
  0.512200436,
  0.487799564,
  0.090849673,
  0.266448802,
  0.14248366,
  0.122222222,
  0.131154684,
  0.118082789,
  0.12875817,
  489,
  9.386503067],
 [1114059000,
  '서울특별시',
  '중구',
  '광희동',
  5255,
  311,
  1060,
  896,
  623,
  800,
  848,
  717,
  0.511512845,
  0.488487155,
  0.059181732,
  0.201712655,
  0.170504282,
  0.118553758,
  0.152235966,
  0.161370124,
  0.136441484,
  4218,
  1.245851114],
 [1114060500,
  '서울특별시',
  '중구',
  '을지로동',
  1738,
  68,
  232,
  312,
  184,
  281,
  391,
  270,
  0.602991945,
  0.397008055,
  0.039125432,
  0.133486766,
  0.179516686,
  0.105868815,
  0.161680092,
  0.224971231,
  0.155350978,
  4024,
  0.431908549],
 [1114061500,
  '서울특별시',
  '중구',
  '신당동',
  7673,
  525,
  1373,
  1351,
  1037,
  1318,
  1108,
  961,
  0.492897172,
  0.507102828,
  0.068421739,
  0.178939137,
  0.176071941,
  0.135149225,
  0.171771146,
  0.14440245,
  0.125244363,
  2143,
  3.580494634],
 [1114062500,
  '서울특별시',
  '중구',
  '다산동',
  13798,
  1278,
  2268,
  2195,
  1899,
  2265,
  2015,
  1878,
  0.486447311,
  0.513552689,
  0.092622119,
  0.164371648,
  0.159081026,
  0.137628642,
  0.164154225,
  0.146035657,
  0.136106682,
  849,
  16.25206125],
 [1114063500,
  '서울특별시',
  '중구',
  '약수동',
  16676,
  1927,
  1992,
  2323,
  2379,
  2763,
  2720,
  2572,
  0.464739746,
  0.535260254,
  0.115555289,
  0.119453106,
  0.139301991,
  0.14266011,
  0.165687215,
  0.163108659,
  0.154233629,
  554,
  30.10108303],
 [1114064500,
  '서울특별시',
  '중구',
  '청구동',
  13588,
  1548,
  1852,
  2129,
  1831,
  2306,
  2069,
  1853,
  0.473800412,
  0.526199588,
  0.113924051,
  0.136296732,
  0.156682367,
  0.134751251,
  0.169708566,
  0.152266706,
  0.136370327,
  410,
  33.14146341],
 [1114065000,
  '서울특별시',
  '중구',
  '신당5동',
  10363,
  1062,
  1650,
  1691,
  1527,
  1846,
  1372,
  1215,
  0.487407121,
  0.512592879,
  0.102479977,
  0.159220303,
  0.163176686,
  0.147351153,
  0.178133745,
  0.132394094,
  0.117244041,
  629,
  16.47535771],
 [1114066500,
  '서울특별시',
  '중구',
  '동화동',
  10266,
  1461,
  1332,
  1299,
  1487,
  1914,
  1512,
  1261,
  0.482758621,
  0.517241379,
  0.142314436,
  0.129748685,
  0.126534191,
  0.144847068,
  0.186440678,
  0.147282291,
  0.122832651,
  442,
  23.22624434],
 [1114067000,
  '서울특별시',
  '중구',
  '황학동',
  12576,
  1198,
  2134,
  2822,
  1807,
  1777,
  1560,
  1278,
  0.476860687,
  0.523139313,
  0.095260814,
  0.169688295,
  0.224395674,
  0.143686387,
  0.141300891,
  0.124045802,
  0.101622137,
  1128,
  11.14893617],
 [1114068000,
  '서울특별시',
  '중구',
  '중림동',
  12035,
  1723,
  1339,
  2115,
  2027,
  1896,
  1544,
  1391,
  0.497299543,
  0.502700457,
  0.143165767,
  0.111258828,
  0.175737432,
  0.168425426,
  0.157540507,
  0.12829248,
  0.11557956,
  646,
  18.63003096],
 [1111051500,
  '서울특별시',
  '종로구',
  '청운효자동',
  11978,
  1886,
  1566,
  1581,
  2075,
  1925,
  1407,
  1538,
  0.461345801,
  0.538654199,
  0.157455335,
  0.130739689,
  0.131991985,
  0.173234263,
  0.160711304,
  0.117465353,
  0.12840207,
  797,
  15.02885822],
 [1111053000,
  '서울특별시',
  '종로구',
  '사직동',
  9372,
  1233,
  1202,
  1447,
  1489,
  1533,
  1207,
  1261,
  0.448143406,
  0.551856594,
  0.1315621,
  0.128254375,
  0.154396073,
  0.158877507,
  0.163572343,
  0.128787879,
  0.134549723,
  2473,
  3.789729074],
 [1111054000,
  '서울특별시',
  '종로구',
  '삼청동',
  2456,
  273,
  320,
  303,
  348,
  385,
  407,
  420,
  0.475570033,
  0.524429967,
  0.111156352,
  0.13029316,
  0.123371336,
  0.141693811,
  0.156758958,
  0.165716612,
  0.171009772,
  783,
  3.136653895],
 [1111055000,
  '서울특별시',
  '종로구',
  '부암동',
  9579,
  1351,
  1227,
  1210,
  1551,
  1682,
  1353,
  1205,
  0.477085291,
  0.522914709,
  0.141037687,
  0.128092703,
  0.126317987,
  0.161916693,
  0.175592442,
  0.141246477,
  0.125796012,
  443,
  21.62302483],
 [1111056000,
  '서울특별시',
  '종로구',
  '평창동',
  18152,
  2727,
  2342,
  2200,
  2690,
  3256,
  2679,
  2258,
  0.465899074,
  0.534100926,
  0.150231379,
  0.129021595,
  0.121198766,
  0.148193037,
  0.179374174,
  0.147587043,
  0.124394006,
  538,
  33.73977695],
 [1111057000,
  '서울특별시',
  '종로구',
  '무악동',
  8259,
  1621,
  907,
  903,
  1389,
  1433,
  1040,
  966,
  0.46506841,
  0.53493159,
  0.196270735,
  0.109819591,
  0.109335271,
  0.168180167,
  0.173507689,
  0.125923235,
  0.116963313,
  186,
  44.40322581],
 [1111058000,
  '서울특별시',
  '종로구',
  '교남동',
  10046,
  1614,
  1205,
  1576,
  1778,
  1590,
  1180,
  1103,
  0.461278121,
  0.538721879,
  0.16066096,
  0.119948238,
  0.15687836,
  0.176985865,
  0.158271949,
  0.117459685,
  0.109794943,
  309,
  32.51132686],
 [1111060000,
  '서울특별시',
  '종로구',
  '가회동',
  4088,
  491,
  475,
  535,
  694,
  709,
  567,
  617,
  0.460861057,
  0.539138943,
  0.120107632,
  0.116193738,
  0.130870841,
  0.169765166,
  0.173434442,
  0.13869863,
  0.15092955,
  624,
  6.551282051],
 [1111061500,
  '서울특별시',
  '종로구',
  '종로1·2·3·4가동',
  7197,
  410,
  932,
  942,
  915,
  1316,
  1398,
  1284,
  0.590662776,
  0.409337224,
  0.056968181,
  0.129498402,
  0.13088787,
  0.127136307,
  0.182853967,
  0.194247603,
  0.17840767,
  9592,
  0.750312761],
 [1111063000,
  '서울특별시',
  '종로구',
  '종로5·6가동',
  5089,
  304,
  1112,
  735,
  557,
  881,
  763,
  737,
  0.534486147,
  0.465513853,
  0.059736687,
  0.218510513,
  0.144429161,
  0.109451759,
  0.173118491,
  0.149931224,
  0.144822165,
  2703,
  1.8827229],
 [1111064000,
  '서울특별시',
  '종로구',
  '이화동',
  7231,
  582,
  1585,
  1221,
  885,
  1096,
  939,
  923,
  0.472825335,
  0.527174665,
  0.080486793,
  0.219195132,
  0.168856313,
  0.122389711,
  0.151569631,
  0.129857558,
  0.127644862,
  1005,
  7.195024876],
 [1111065000,
  '서울특별시',
  '종로구',
  '혜화동',
  16383,
  1893,
  4366,
  2015,
  2112,
  2377,
  1665,
  1955,
  0.482451321,
  0.517548679,
  0.115546603,
  0.266495758,
  0.122993347,
  0.128914118,
  0.145089422,
  0.101629738,
  0.119331014,
  1430,
  11.45664336],
 [1111067000,
  '서울특별시',
  '종로구',
  '창신1동',
  4891,
  345,
  597,
  546,
  590,
  1001,
  1021,
  791,
  0.536904519,
  0.463095481,
  0.070537722,
  0.122060928,
  0.111633613,
  0.120629728,
  0.204661623,
  0.208750767,
  0.161725618,
  994,
  4.920523139],
 [1111068000,
  '서울특별시',
  '종로구',
  '창신2동',
  7911,
  633,
  1102,
  924,
  975,
  1775,
  1391,
  1111,
  0.515990393,
  0.484009607,
  0.080015169,
  0.139299709,
  0.116799393,
  0.123246113,
  0.224371129,
  0.175831121,
  0.140437366,
  321,
  24.64485981],
 [1111069000,
  '서울특별시',
  '종로구',
  '창신3동',
  6575,
  828,
  905,
  926,
  881,
  1227,
  1038,
  770,
  0.493079848,
  0.506920152,
  0.125931559,
  0.137642586,
  0.140836502,
  0.133992395,
  0.18661597,
  0.157870722,
  0.117110266,
  125,
  52.6],
 [1111070000,
  '서울특별시',
  '종로구',
  '숭인1동',
  5837,
  583,
  749,
  794,
  861,
  1147,
  928,
  775,
  0.481583005,
  0.518416995,
  0.099880075,
  0.128319342,
  0.136028782,
  0.147507281,
  0.196505054,
  0.15898578,
  0.132773685,
  207,
  28.19806763],
 [1111071000,
  '서울특별시',
  '종로구',
  '숭인2동',
  9639,
  591,
  2210,
  1612,
  1179,
  1624,
  1369,
  1054,
  0.502956738,
  0.497043262,
  0.061313414,
  0.229276896,
  0.167237265,
  0.122315593,
  0.168482208,
  0.142027181,
  0.109347443,
  918,
  10.5],
 [2818563000,
  '인천광역시',
  '연수구',
  '옥련1동',
  19332,
  3100,
  2534,
  2186,
  3050,
  3721,
  2658,
  2083,
  0.494982413,
  0.505017587,
  0.160355887,
  0.131078005,
  0.113076764,
  0.157769501,
  0.192478792,
  0.137492241,
  0.10774881,
  1105,
  17.49502262],
 [2818564000,
  '인천광역시',
  '연수구',
  '옥련2동',
  20365,
  3489,
  2813,
  2356,
  3274,
  3889,
  2692,
  1852,
  0.493150012,
  0.506849988,
  0.171323349,
  0.138129143,
  0.115688682,
  0.16076602,
  0.190964891,
  0.132187577,
  0.090940339,
  717,
  28.40306834],
 [2818575000,
  '인천광역시',
  '연수구',
  '선학동',
  17176,
  1896,
  2358,
  2185,
  2344,
  3264,
  3167,
  1962,
  0.517466232,
  0.482533768,
  0.110386586,
  0.137284583,
  0.127212389,
  0.136469492,
  0.190032604,
  0.184385189,
  0.114229157,
  740,
  23.21081081],
 [2818576100,
  '인천광역시',
  '연수구',
  '연수1동',
  19404,
  2355,
  2971,
  2483,
  3084,
  3941,
  2805,
  1765,
  0.547515976,
  0.452484024,
  0.121366729,
  0.15311276,
  0.127963307,
  0.158936302,
  0.203102453,
  0.144557823,
  0.090960627,
  1136,
  17.08098592],
 [2818576200,
  '인천광역시',
  '연수구',
  '연수2동',
  21168,
  2937,
  3161,
  3240,
  2998,
  3796,
  3044,
  1992,
  0.491402116,
  0.508597884,
  0.138747166,
  0.149329176,
  0.153061224,
  0.141628874,
  0.179327286,
  0.143801965,
  0.094104308,
  1482,
  14.28340081],
 [2818576300,
  '인천광역시',
  '연수구',
  '연수3동',
  16112,
  2047,
  2153,
  2144,
  2093,
  2958,
  2676,
  2041,
  0.474491063,
  0.525508937,
  0.127048163,
  0.13362711,
  0.13306852,
  0.129903178,
  0.183589871,
  0.166087388,
  0.12667577,
  210,

In [16]:
#정규화하는 함수
#https://jimmy-ai.tistory.com/81
def np_norm(for_norm):
    import numpy as np
    import numpy.linalg as LA

    #for_norm = df_concat.iloc[:,5:].values.tolist()
    df_norm = for_norm/LA.norm(for_norm,ord=2, axis=0)
    return df_norm

In [17]:
#정규화한 형태
df_concat_iloc = df_concat.iloc[:,4:]
np_norm(df_concat_iloc)

,총인구수,20대미만,20대,30대,40대,50대,60대,70대이상,남여성비(남),남여성비(여),연령비_20미만,연령비_20,연령비_30,연령비_40,연령비_50,연령비_60,연령비_70이상,운영가맹점수,가맹점당인구수
380,0.06279,0.03640,0.05355,0.05243,0.05110,0.06882,0.09660,0.09373,0.09527,0.09690,0.07159,0.07822,0.08705,0.08772,0.09835,0.12456,0.10622,0.02748,0.07855
381,0.12093,0.09656,0.12666,0.12037,0.11156,0.11332,0.13308,0.13037,0.09247,0.09963,0.09860,0.09606,0.10377,0.09943,0.08409,0.08910,0.07671,0.04414,0.09418
382,0.06118,0.03841,0.06131,0.05074,0.04994,0.07029,0.07957,0.08504,0.09832,0.09392,0.07754,0.09191,0.08647,0.08799,0.10309,0.10530,0.09891,0.03298,0.06378
383,0.09136,0.06803,0.07483,0.07869,0.08109,0.10096,0.11422,0.12599,0.09571,0.09647,0.09195,0.07511,0.08979,0.09566,0.09916,0.10122,0.09812,0.03275,0.09590
384,0.09229,0.05975,0.07742,0.06306,0.07401,0.10942,0.13196,0.15415,0.09942,0.09285,0.07994,0.07693,0.07123,0.08644,0.10639,0.11577,0.11884,0.02816,0.11267
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1451,0.08241,0.10303,0.06735,0.06927,0.08453,0.08483,0.06660,0.06535,0.09475,0.09740,0.15438,0.07494,0.08763,0.11055,0.09236,0.06543,0.05642,0.01507,0.18797
1452,0.06754,0.06161,0.06855,0.05566,0.05330,0.07940,0.07440,0.07023,0.09430,0.09785,0.11265,0.09309,0.08591,0.08506,0.10549,0.08919,0.07399,0.04595,0.05052
1453,0.07319,0.07239,0.06855,0.07324,0.06049,0.08009,0.06994,0.06900,0.09610,0.09609,0.12213,0.08589,0.10432,0.08907,0.09818,0.07736,0.06707,0.00691,0.36400
1454,0.04495,0.02949,0.04190,0.04695,0.03723,0.04703,0.05709,0.05559,0.10172,0.09061,0.08103,0.08549,0.10891,0.08929,0.09390,0.10284,0.08800,0.04335,0.03565
1455,0.03646,0.03245,0.03586,0.02842,0.03162,0.04089,0.03648,0.04774,0.09510,0.09706,0.10990,0.09021,0.08126,0.09348,0.10062,0.08101,0.09316,0.00969,0.12936

In [18]:
#기준 행정동의 요소들 추출
print(gu,dong)
for row in df_concat_list :
    if (gu in row[2]) and (dong in row[3]) : 
        lista = np.array((row[4:]), dtype=float)

#       정규화 하기 전(비교 차원)
#       print(gu,dong,lista)
        
        #정규화 한 후
        home = np_norm(lista)  # ➊ 사용자로부터 입력받은 지역의 인구 비율을 home에 저장
        print(gu,dong,home)

종로구 삼청동
종로구 삼청동 [8.95304442e-01 9.95187755e-02 1.16652044e-01 1.10454905e-01
 1.26859098e-01 1.40346991e-01 1.48366819e-01 1.53105808e-01
 1.73363177e-04 1.91174462e-04 4.05206741e-05 4.74967609e-05
 4.49734956e-05 5.16527273e-05 5.71445405e-05 6.04099425e-05
 6.23394985e-05 2.85432971e-01 1.14342841e-03]

In [19]:
# 그 외 행정동 요소들 추출
for row in df_concat_list :  # ➏ 전체 데이터에 대해 반복
    #print(row)
    away = np_norm(np.array((row[4:]), dtype=float))   # ➋ 그런 다음 다른 지역의 인구 비율을 away에 저장한 후
    #print(away)
    
    #자승제곱법 적용(차이의 제곱의 합)
    s = np.sum((home-away)**2)  # ➌ home에 저장된 값과 away에 저장된 값의 차이의 합을 계산
    
    #자승제곱값을 새로운 컬럼에 추가
    row.append(s)
print(df_concat_list)

[[1171051000, '서울특별시', '송파구', '풍납1동', 12869, 1428, 1553, 1771, 1813, 2205, 2428, 1671, 0.489548527, 0.510451473, 0.110964333, 0.120677597, 0.13761753, 0.140881187, 0.171341985, 0.188670448, 0.129846919, 485, 26.53402062, 0.06659635015126833], [1171052000, '서울특별시', '송파구', '풍납2동', 24785, 3788, 3673, 4066, 3958, 3631, 3345, 2324, 0.475166431, 0.524833569, 0.152834376, 0.148194472, 0.164050837, 0.159693363, 0.146499899, 0.134960662, 0.093766391, 779, 31.81643132, 0.07651629346390358], [1171053100, '서울특별시', '송파구', '거여1동', 12539, 1507, 1778, 1714, 1772, 2252, 2000, 1516, 0.505223702, 0.494776298, 0.120185023, 0.141797592, 0.136693516, 0.141319084, 0.179599649, 0.159502353, 0.120902783, 582, 21.54467354, 0.06316303203013397], [1171053200, '서울특별시', '송파구', '거여2동', 18726, 2669, 2170, 2658, 2877, 3235, 2871, 2246, 0.491829542, 0.508170458, 0.142529104, 0.115881662, 0.141941685, 0.153636655, 0.172754459, 0.153316245, 0.11994019, 578, 32.39792388, 0.07146919738560883], [1171054000, '서울특별시', '송파구', '마천1동', 18916, 2344, 2245, 2130, 2626, 3506, 3317, 2748, 0.510890252, 0.489109748, 0.123916261, 0.118682597, 0.112603087, 0.138824276, 0.185345739, 0.175354198, 0.145273842, 497, 38.06036217, 0.07144808277105882], [1171055000, '서울특별시', '송파구', '마천2동', 18713, 2022, 2322, 2156, 2593, 3525, 3533, 2562, 0.509592262, 0.490407738, 0.108053225, 0.124084861, 0.115214022, 0.138566772, 0.18837172, 0.18879923, 0.136910169, 910, 20.56373626, 0.06165433241622742], [1171056100, '서울특별시', '송파구', '방이1동', 15682, 2571, 2355, 2227, 2481, 2668, 2073, 1307, 0.48176253, 0.51823747, 0.163945925, 0.150172172, 0.142009948, 0.158206861, 0.170131361, 0.132189772, 0.083343961, 1060, 14.79433962, 0.06172894585529406], [1171056200, '서울특별시', '송파구', '방이2동', 26489, 2295, 5366, 6230, 3645, 3572, 3260, 2121, 0.464494696, 0.535505304, 0.086639737, 0.202574654, 0.235191966, 0.137604289, 0.134848428, 0.123069954, 0.080070973, 2255, 11.74678492, 0.06810314163027734], [1171056600, '서울특별시', '송파구', '오륜동', 18061, 3809, 2106, 1661, 3146, 3131, 2623, 1585, 0.488566525, 0.511433475, 0.210896407, 0.116604839, 0.091966115, 0.174187476, 0.173356957, 0.145230054, 0.087758153, 394, 45.84010152, 0.08848859566797605], [1171057000, '서울특별시', '송파구', '오금동', 38446, 5687, 5226, 5444, 5615, 6763, 5873, 3838, 0.484731832, 0.515268168, 0.14792176, 0.135930916, 0.141601207, 0.146049004, 0.175909067, 0.152759715, 0.099828331, 1541, 24.94873459, 0.06931692902569093], [1171058000, '서울특별시', '송파구', '송파1동', 23845, 2374, 4334, 5326, 3343, 3323, 3073, 2072, 0.466722583, 0.533277417, 0.099559656, 0.181757182, 0.223359195, 0.140197106, 0.139358356, 0.128873978, 0.086894527, 1729, 13.79120879, 0.066994846823159], [1171059000, '서울특별시', '송파구', '송파2동', 19130, 3265, 2608, 2737, 2999, 3129, 2718, 1674, 0.482017773, 0.517982227, 0.170674334, 0.136330371, 0.143073706, 0.156769472, 0.163565081, 0.142080502, 0.087506534, 744, 25.71236559, 0.07358397658027709], [1171060000, '서울특별시', '송파구', '석촌동', 31584, 3286, 5354, 6799, 4800, 4632, 3971, 2742, 0.477013678, 0.522986322, 0.10404002, 0.169516211, 0.215267224, 0.151975684, 0.146656535, 0.125728217, 0.086816109, 2235, 14.13154362, 0.06555508170001814], [1171061000, '서울특별시', '송파구', '삼전동', 30325, 3353, 5145, 6382, 4975, 4323, 3709, 2438, 0.47004122, 0.52995878, 0.110568838, 0.169661995, 0.210453421, 0.164056059, 0.142555647, 0.122308326, 0.080395713, 1607, 18.87056627, 0.07398301450198319], [1171062000, '서울특별시', '송파구', '가락본동', 26252, 3335, 3908, 4599, 3759, 4558, 3823, 2270, 0.49592412, 0.50407588, 0.12703794, 0.148864848, 0.175186652, 0.14318909, 0.173624867, 0.145627, 0.086469602, 2269, 11.56985456, 0.05277169626647326], [1171063100, '서울특별시', '송파구', '가락1동', 27265, 5410, 3092, 4793, 4508, 3957, 3611, 1894, 0.484247203, 0.515752797, 0.198422886, 0.113405465, 0.175793141, 0.16534018, 0.14513112, 0.132440858, 0.069466349, 1655, 16.47432024, 0.07297811373003968], [1171063200, '서울특별시', '송파구', '가락2동', 32229, 5809, 4390, 4643, 5470, 5193, 4244, 2480, 0.490862267, 0.509137733, 0.180241397, 0.136212728, 0.144062801, 0.16972292, 0.161128176, 0.131682646, 0.076949331, 1338, 24.08744395, 0.07593757969250974], [1171064100, '서울특별시', '송파구', '문정1동', 20012, 2678, 3088, 3414, 2817, 3277, 3028, 1710, 0.495802518, 0.504197482, 0.133819708, 0.154307416, 0.170597641, 0.140765541, 0.163751749, 0.151309214, 0.085448731, 960, 20.84583333, 0.06868299084335786], [1171064200, '서울특별시', '송파구', '문정2동', 28871, 2939, 5099, 7250, 4365, 3503, 3244, 2471, 0.459492224, 0.540507776, 0.101797652, 0.17661321, 0.251117038, 0.151189775, 0.121332825, 0.112361886, 0.085587614, 3654, 7.90120416, 0.05444643134514635], [1171064600, '서울특별시', '송파구', '장지동', 29534, 4858, 3978, 4602, 4629, 4784, 4042, 2641, 0.483442812, 0.516557188, 0.164488386, 0.134692219, 0.15582041, 0.156734611, 0.161982799, 0.136859213, 0.089422361, 909, 32.49064906, 0.077337515108426], [1171064700, '서울특별시', '송파구', '위례동', 39095, 11513, 3586, 6816, 7710, 4686, 2971, 1813, 0.487069958, 0.512930042, 0.294487786, 0.091725285, 0.174344545, 0.19721192, 0.119861875, 0.075994373, 0.046374217, 663, 58.9668175, 0.12826492772043138], [1171065000, '서울특별시', '송파구', '잠실본동', 27953, 2856, 4992, 6017, 4316, 4031, 3498, 2243, 0.474510786, 0.525489214, 0.102171502, 0.178585483, 0.215254177, 0.154402032, 0.144206346, 0.125138626, 0.080241835, 2621, 10.66501335, 0.05830436076550221], [1171067000, '서울특별시', '송파구', '잠실2동', 35036, 9508, 3269, 3512, 8332, 5124, 3003, 2288, 0.478250942, 0.521749058, 0.271378011, 0.09330403, 0.100239753, 0.237812536, 0.146249572, 0.085711839, 0.065304258, 706, 49.62606232, 0.11759500078533093], [1171068000, '서울특별시', '송파구', '잠실3동', 34338, 7045, 3685, 3916, 6186, 5249, 4783, 3474, 0.475770284, 0.524229716, 0.205166288, 0.107315511, 0.114042751, 0.180150271, 0.152862718, 0.139291747, 0.101170715, 878, 39.10933941, 0.0839222314877702], [1171069000, '서울특별시', '송파구', '잠실4동', 21318, 5048, 1944, 2716, 4403, 3015, 2536, 1656, 0.479829252, 0.520170748, 0.236795197, 0.091190543, 0.127404072, 0.206539075, 0.141429778, 0.118960503, 0.077680833, 291, 73.25773196, 0.10319283999853154], [1171071000, '서울특별시', '송파구', '잠실6동', 16775, 3104, 1931, 2117, 2771, 2666, 2479, 1707, 0.473621461, 0.526378539, 0.185037258, 0.115111773, 0.126199702, 0.165186289, 0.158926975, 0.147779434, 0.101758569, 1349, 12.43513714, 0.055328588684873045], [1171072000, '서울특별시', '송파구', '잠실7동', 9550, 1507, 1225, 934, 1300, 1676, 1480, 1428, 0.466387435, 0.533612565, 0.157801047, 0.128272251, 0.097801047, 0.136125654, 0.175497382, 0.154973822, 0.149528796, 113, 84.51327434, 0.08023075687955002], [2811052000, '인천광역시', '중구', '연안동', 6145, 542, 619, 625, 774, 1228, 1365, 992, 0.541253051, 0.458746949, 0.08820179, 0.100732303, 0.101708706, 0.125956062, 0.199837266, 0.222131814, 0.161432059, 1184, 5.190033784, 0.01851903188106985], [2811053000, '인천광역시', '중구', '신포동', 5086, 579, 517, 519, 778, 866, 854, 973, 0.510224145, 0.489775855, 0.113841919, 0.101651593, 0.102044829, 0.152968934, 0.170271333, 0.167911915, 0.191309477, 1065, 4.775586854, 0.010983414050568244], [2811054000, '인천광역시', '중구', '신흥동', 13241, 1912, 1602, 1551, 2013, 2247, 2121, 1795, 0.50857186, 0.49142814, 0.14439997, 0.120987841, 0.117136168, 0.152027792, 0.169700174, 0.160184276, 0.135563779, 846, 15.65130024, 0.05491821585876697], [2811056000, '인천광역시', '중구', '도원동', 3925, 360, 424, 345, 525, 705, 773, 793, 0.509808917, 0.490191083, 0.091719745, 0.108025478, 0.087898089, 0.133757962, 0.179617834, 0.196942675, 0.202038217, 143, 27.44755245, 0.06885503298582948], [2811057000, '인천광역시', '중구', '율목동', 3192, 253, 328, 281, 446, 616, 627, 641, 0.515037594, 0.484962406, 0.079260652, 0.102756892, 0.088032581, 0.139724311, 0.192982456, 0.196428571, 0.200814536, 125, 25.536, 0.06885486238794727], [2811058500, '인천광역시', '중구', '동인천동', 5818, 467, 588, 643, 740, 1077, 1132, 1171, 0.529907185, 0.470092815, 0.080268133, 0.101065658, 0.110519079, 0.127191475, 0.18511516, 0.19456858, 0.201271915, 1038, 5.605009634, 0.019501993731362854], [2811061500, '인천광역시', '중구', '개항동', 7022, 677, 740, 675, 933, 1256, 1384, 1357, 0.500996867, 0.499003133, 0.096411279, 0.105383082, 0.09612646, 0.132868129, 0.17886642, 0.197094845, 0.193249786, 561, 12.51693405, 0.04915890089926451], [2811062000, '인천광역시', '중구', '영종동', 19131, 2732, 2512, 2997, 3140, 3269, 2778, 1703, 0.546495217, 0.453504783, 0.142804872, 0.131305211, 0.156656735, 0.164131514, 0.170874497, 0.145209346, 0.089017824, 837, 22.85663082, 0.06981660366682389], [2811062200, '인천광역시', '중구', '영종1동', 44046, 12063, 3720, 8612, 9816, 4795, 3084, 1956, 0.502156836, 0.497843164, 0.273872769, 0.084457158, 0.195522862, 0.222857921, 0.108863461, 0.070017709, 0.044408119, 1319, 33.39347991, 0.12362458712753724], [2811062800, '인천광역시', '중구', '운서동', 32080, 5040, 7645, 5466, 5623, 4318, 2122, 1866, 0.530174564, 0.469825436, 0.157107232, 0.238310474, 0.170386534, 0.175280549, 0.134600998, 0.066147132, 0.058167082, 1789, 17.93180548, 0.08955978411693899], [2811063000, '인천광역시', '중구', '용유동', 3947, 183, 245, 277, 446, 853, 1076, 867, 0.556625285, 0.443374715, 0.046364327, 0.06207246, 0.070179883, 0.112997213, 0.216113504, 0.27261211, 0.219660502, 1008, 3.915674603, 0.026995768971933457], [1114052000, '서울특별시', '중구', '소공동', 2250, 294, 251, 501, 504, 305, 243, 152, 0.478666667, 0.521333333, 0.130666667, 0.111555556, 0.222666667, 0.224, 0.135555556, 0.108, 0.067555556, 2518, 0.893566322, 0.2769940774199068], [1114054000, '서울특별시', '중구', '회현동', 4784, 389, 492, 520, 648, 891, 1031, 813, 0.52006689, 0.47993311, 0.081312709, 0.102842809, 0.108695652, 0.135451505, 0.186245819, 0.215510033, 0.169941472, 4422, 1.08186341, 0.1774043597714158], [1114055000, '서울특별시', '중구', '명동', 2884, 209, 384, 403, 406, 489, 519, 474, 0.437586685, 0.562413315, 0.072468793, 0.133148405, 0.139736477, 0.140776699, 0.169556172, 0.179958391, 0.164355062, 3808, 0.757352941, 0.3494831717861781], [1114057000, '서울특별시', '중구', '필동', 4023, 363, 727, 675, 459, 590, 609, 600, 0.508327119, 0.491672881, 0.090231171, 0.180710912, 0.167785235, 0.11409396, 0.146656724, 0.151379567, 0.149142431, 1688, 2.383293839, 0.012056726930348457], [1114058000, '서울특별시', '중구', '장충동', 4590, 417, 1223, 654, 561, 602, 542, 591, 0.512200436, 0.487799564, 0.090849673, 0.266448802, 0.14248366, 0.122222222, 0.131154684, 0.118082789, 0.12875817, 489, 9.386503067, 0.05647595809357282], [1114059000, '서울특별시', '중구', '광희동', 5255, 311, 1060, 896, 623, 800, 848, 717, 0.511512845, 0.488487155, 0.059181732, 0.201712655, 0.170504282, 0.118553758, 0.152235966, 0.161370124, 0.136441484, 4218, 1.245851114, 0.13049181065654106], [1114060500, '서울특별시', '중구', '을지로동', 1738, 68, 232, 312, 184, 281, 391, 270, 0.602991945, 0.397008055, 0.039125432, 0.133486766, 0.179516686, 0.105868815, 0.161680092, 0.224971231, 0.155350978, 4024, 0.431908549, 0.677707151396059], [1114061500, '서울특별시', '중구', '신당동', 7673, 525, 1373, 1351, 1037, 1318, 1108, 961, 0.492897172, 0.507102828, 0.068421739, 0.178939137, 0.176071941, 0.135149225, 0.171771146, 0.14440245, 0.125244363, 2143, 3.580494634, 0.009111968771847796], [1114062500, '서울특별시', '중구', '다산동', 13798, 1278, 2268, 2195, 1899, 2265, 2015, 1878, 0.486447311, 0.513552689, 0.092622119, 0.164371648, 0.159081026, 0.137628642, 0.164154225, 0.146035657, 0.136106682, 849, 16.25206125, 0.05733066742025434], [1114063500, '서울특별시', '중구', '약수동', 16676, 1927, 1992, 2323, 2379, 2763, 2720, 2572, 0.464739746, 0.535260254, 0.115555289, 0.119453106, 0.139301991, 0.14266011, 0.165687215, 0.163108659, 0.154233629, 554, 30.10108303, 0.06704773773083245], [1114064500, '서울특별시', '중구', '청구동', 13588, 1548, 1852, 2129, 1831, 2306, 2069, 1853, 0.473800412, 0.526199588, 0.113924051, 0.136296732, 0.156682367, 0.134751251, 0.169708566, 0.152266706, 0.136370327, 410, 33.14146341, 0.07017332147629086], [1114065000, '서울특별시', '중구', '신당5동', 10363, 1062, 1650, 1691, 1527, 1846, 1372, 1215, 0.487407121, 0.512592879, 0.102479977, 0.159220303, 0.163176686, 0.147351153, 0.178133745, 0.132394094, 0.117244041, 629, 16.47535771, 0.059804955590612774], [1114066500, '서울특별시', '중구', '동화동', 10266, 1461, 1332, 1299, 1487, 1914, 1512, 1261, 0.482758621, 0.517241379, 0.142314436, 0.129748685, 0.126534191, 0.144847068, 0.186440678, 0.147282291, 0.122832651, 442, 23.22624434, 0.06559625149986338], [1114067000, '서울특별시', '중구', '황학동', 12576, 1198, 2134, 2822, 1807, 1777, 1560, 1278, 0.476860687, 0.523139313, 0.095260814, 0.169688295, 0.224395674, 0.143686387, 0.141300891, 0.124045802, 0.101622137, 1128, 11.14893617, 0.057958908840646924], [1114068000, '서울특별시', '중구', '중림동', 12035, 1723, 1339, 2115, 2027, 1896, 1544, 1391, 0.497299543, 0.502700457, 0.143165767, 0.111258828, 0.175737432, 0.168425426, 0.157540507, 0.12829248, 0.11557956, 646, 18.63003096, 0.06480765736893396], [1111051500, '서울특별시', '종로구', '청운효자동', 11978, 1886, 1566, 1581, 2075, 1925, 1407, 1538, 0.461345801, 0.538654199, 0.157455335, 0.130739689, 0.131991985, 0.173234263, 0.160711304, 0.117465353, 0.12840207, 797, 15.02885822, 0.057628576321627926], [1111053000, '서울특별시', '종로구', '사직동', 9372, 1233, 1202, 1447, 1489, 1533, 1207, 1261, 0.448143406, 0.551856594, 0.1315621, 0.128254375, 0.154396073, 0.158877507, 0.163572343, 0.128787879, 0.134549723, 2473, 3.789729074, 0.005856571158855432], [1111054000, '서울특별시', '종로구', '삼청동', 2456, 273, 320, 303, 348, 385, 407, 420, 0.475570033, 0.524429967, 0.111156352, 0.13029316, 0.123371336, 0.141693811, 0.156758958, 0.165716612, 0.171009772, 783, 3.136653895, 0.0], [1111055000, '서울특별시', '종로구', '부암동', 9579, 1351, 1227, 1210, 1551, 1682, 1353, 1205, 0.477085291, 0.522914709, 0.141037687, 0.128092703, 0.126317987, 0.161916693, 0.175592442, 0.141246477, 0.125796012, 443, 21.62302483, 0.06394760012523747], [1111056000, '서울특별시', '종로구', '평창동', 18152, 2727, 2342, 2200, 2690, 3256, 2679, 2258, 0.465899074, 0.534100926, 0.150231379, 0.129021595, 0.121198766, 0.148193037, 0.179374174, 0.147587043, 0.124394006, 538, 33.73977695, 0.07197093807514818], [1111057000, '서울특별시', '종로구', '무악동', 8259, 1621, 907, 903, 1389, 1433, 1040, 966, 0.46506841, 0.53493159, 0.196270735, 0.109819591, 0.109335271, 0.168180167, 0.173507689, 0.125923235, 0.116963313, 186, 44.40322581, 0.082790244474619], [1111058000, '서울특별시', '종로구', '교남동', 10046, 1614, 1205, 1576, 1778, 1590, 1180, 1103, 0.461278121, 0.538721879, 0.16066096, 0.119948238, 0.15687836, 0.176985865, 0.158271949, 0.117459685, 0.109794943, 309, 32.51132686, 0.07680273553198869], [1111060000, '서울특별시', '종로구', '가회동', 4088, 491, 475, 535, 694, 709, 567, 617, 0.460861057, 0.539138943, 0.120107632, 0.116193738, 0.130870841, 0.169765166, 0.173434442, 0.13869863, 0.15092955, 624, 6.551282051, 0.023910619568549413], [1111061500, '서울특별시', '종로구', '종로1·2·3·4가동', 7197, 410, 932, 942, 915, 1316, 1398, 1284, 0.590662776, 0.409337224, 0.056968181, 0.129498402, 0.13088787, 0.127136307, 0.182853967, 0.194247603, 0.17840767, 9592, 0.750312761, 0.3545747910092987], [1111063000, '서울특별시', '종로구', '종로5·6가동', 5089, 304, 1112, 735, 557, 881, 763, 737, 0.534486147, 0.465513853, 0.059736687, 0.218510513, 0.144429161, 0.109451759, 0.173118491, 0.149931224, 0.144822165, 2703, 1.8827229, 0.0382937601290962], [1111064000, '서울특별시', '종로구', '이화동', 7231, 582, 1585, 1221, 885, 1096, 939, 923, 0.472825335, 0.527174665, 0.080486793, 0.219195132, 0.168856313, 0.122389711, 0.151569631, 0.129857558, 0.127644862, 1005, 7.195024876, 0.037756160783507485], [1111065000, '서울특별시', '종로구', '혜화동', 16383, 1893, 4366, 2015, 2112, 2377, 1665, 1955, 0.482451321, 0.517548679, 0.115546603, 0.266495758, 0.122993347, 0.128914118, 0.145089422, 0.101629738, 0.119331014, 1430, 11.45664336, 0.06456838070318643], [1111067000, '서울특별시', '종로구', '창신1동', 4891, 345, 597, 546, 590, 1001, 1021, 791, 0.536904519, 0.463095481, 0.070537722, 0.122060928, 0.111633613, 0.120629728, 0.204661623, 0.208750767, 0.161725618, 994, 4.920523139, 0.015877422122472482], [1111068000, '서울특별시', '종로구', '창신2동', 7911, 633, 1102, 924, 975, 1775, 1391, 1111, 0.515990393, 0.484009607, 0.080015169, 0.139299709, 0.116799393, 0.123246113, 0.224371129, 0.175831121, 0.140437366, 321, 24.64485981, 0.06888150820457035], [1111069000, '서울특별시', '종로구', '창신3동', 6575, 828, 905, 926, 881, 1227, 1038, 770, 0.493079848, 0.506920152, 0.125931559, 0.137642586, 0.140836502, 0.133992395, 0.18661597, 0.157870722, 0.117110266, 125, 52.6, 0.07716504627149735], [1111070000, '서울특별시', '종로구', '숭인1동', 5837, 583, 749, 794, 861, 1147, 928, 775, 0.481583005, 0.518416995, 0.099880075, 0.128319342, 0.136028782, 0.147507281, 0.196505054, 0.15898578, 0.132773685, 207, 28.19806763, 0.06822789698894748], [1111071000, '서울특별시', '종로구', '숭인2동', 9639, 591, 2210, 1612, 1179, 1624, 1369, 1054, 0.502956738, 0.497043262, 0.061313414, 0.229276896, 0.167237265, 0.122315593, 0.168482208, 0.142027181, 0.109347443, 918, 10.5, 0.056134409864267536], [2818563000, '인천광역시', '연수구', '옥련1동', 19332, 3100, 2534, 2186, 3050, 3721, 2658, 2083, 0.494982413, 0.505017587, 0.160355887, 0.131078005, 0.113076764, 0.157769501, 0.192478792, 0.137492241, 0.10774881, 1105, 17.49502262, 0.06290666884152185], [2818564000, '인천광역시', '연수구', '옥련2동', 20365, 3489, 2813, 2356, 3274, 3889, 2692, 1852, 0.493150012, 0.506849988, 0.171323349, 0.138129143, 0.115688682, 0.16076602, 0.190964891, 0.132187577, 0.090940339, 717, 28.40306834, 0.07618834144972468], [2818575000, '인천광역시', '연수구', '선학동', 17176, 1896, 2358, 2185, 2344, 3264, 3167, 1962, 0.517466232, 0.482533768, 0.110386586, 0.137284583, 0.127212389, 0.136469492, 0.190032604, 0.184385189, 0.114229157, 740, 23.21081081, 0.06580299750387066], [2818576100, '인천광역시', '연수구', '연수1동', 19404, 2355, 2971, 2483, 3084, 3941, 2805, 1765, 0.547515976, 0.452484024, 0.121366729, 0.15311276, 0.127963307, 0.158936302, 0.203102453, 0.144557823, 0.090960627, 1136, 17.08098592, 0.0632240747555191], [2818576200, '인천광역시', '연수구', '연수2동', 21168, 2937, 3161, 3240, 2998, 3796, 3044, 1992, 0.491402116, 0.508597884, 0.138747166, 0.149329176, 0.153061224, 0.141628874, 0.179327286, 0.143801965, 0.094104308, 1482, 14.28340081, 0.05747606631314511], [2818576300, '인천광역시', '연수구', '연수3동', 16112, 2047, 2153, 2144, 2093, 2958, 2676, 2041, 0.474491063, 0.525508937, 0.127048163, 0.13362711, 0.13306852, 0.129903178, 0.183589871, 0.166087388, 0.12667577, 210, 76.72380952, 0.07906612983881087], [2818576600, '인천광역시', '연수구', '청학동', 24815, 2818, 3336, 3073, 3474, 5143, 4149, 2822, 0.518476728, 0.481523272, 0.113560347, 0.134434818, 0.123836389, 0.13999597, 0.207253677, 0.16719726, 0.113721539, 1242, 19.97987118, 0.0635549176153077], [2818578000, '인천광역시', '연수구', '동춘1동', 25462, 4947, 3293, 3635, 4180, 4642, 3264, 1501, 0.49179169, 0.50820831, 0.194289529, 0.129329982, 0.142761763, 0.164166208, 0.182310895, 0.12819103, 0.058950593, 730, 34.87945205, 0.08730960781875052], [2818579000, '인천광역시', '연수구', '동춘2동', 18328, 3180, 2531, 2619, 2779, 3486, 2388, 1345, 0.485541248, 0.514458752, 0.17350502, 0.138094718, 0.142896115, 0.151625928, 0.190200786, 0.130292449, 0.073384985, 815, 22.48834356, 0.07481898544645371], [2818579500, '인천광역시', '연수구', '동춘3동', 18558, 4186, 2491, 1748, 3236, 3403, 2132, 1362, 0.486420951, 0.513579049, 0.225563099, 0.134227826, 0.094191184, 0.174372238, 0.183371053, 0.114883069, 0.073391529, 559, 33.19856887, 0.09109148336232424], [2818582000, '인천광역시', '연수구', '송도1동', 37659, 8380, 6423, 4290, 6543, 6417, 3736, 1870, 0.489869619, 0.510130381, 0.222523168, 0.170556839, 0.113916992, 0.173743328, 0.170397515, 0.099206033, 0.049656125, 2121, 17.7553041, 0.0845689485631381], [2818583000, '인천광역시', '연수구', '송도2동', 36729, 11111, 3626, 4212, 8508, 5665, 2436, 1171, 0.490892755, 0.509107245, 0.302513001, 0.09872308, 0.114677775, 0.231642571, 0.154237796, 0.066323613, 0.031882164, 1861, 19.73616335, 0.11970785015048005], [2818584000, '인천광역시', '연수구', '송도3동', 49052, 12770, 6127, 9014, 10052, 6302, 3247, 1540, 0.490357172, 0.509642828, 0.26033597, 0.124908261, 0.183764169, 0.204925385, 0.128475903, 0.066195058, 0.031395254, 1611, 30.44816884, 0.11612683615323122], [2818585000, '인천광역시', '연수구', '송도4동', 25468, 6787, 2792, 4510, 5363, 3515, 1780, 721, 0.49485629, 0.50514371, 0.266491283, 0.109627768, 0.177

In [20]:
#3. sum((기준 행정동 요소값 - 각 행정동 값)**2)
df4 = pd.DataFrame(df_concat_list)
df4.columns = ['행정동코드', '시도명', '시군구명', '행정동명', '총인구수', '20대미만', '20대', '30대', '40대',
       '50대', '60대', '70대이상', '남여성비(남)', '남여성비(여)', '연령비_20미만', '연령비_20',
       '연령비_30', '연령비_40', '연령비_50', '연령비_60', '연령비_70이상', '운영가맹점수',
       '가맹점당인구수','차이제곱의합']

#4. 절대값으로 orderby 
df4 = df4.sort_values('차이제곱의합',ascending=True) #key=lambda col: abs(col)
print(len(df4))
df4[['행정동코드','시도명','시군구명','행정동명','차이제곱의합']].head(5)

108

         행정동코드    시도명 시군구명    행정동명  차이제곱의합
55  1111054000  서울특별시  종로구     삼청동 0.00000
54  1111053000  서울특별시  종로구     사직동 0.00586
99  1120069000  서울특별시  성동구  성수2가3동 0.00807
45  1114061500  서울특별시   중구     신당동 0.00911
28  2811053000  인천광역시   중구     신포동 0.01098

In [21]:
df4.to_csv('종로구삼청동_유사지역_list_220801.csv',encoding = 'UTF-8-sig', index=False)